### ISSUE TITLE
add wildcard for class-names in config

### ISSUE THREAD

**Issue by aka47** [NejRemeslnici/tailwind-sorter#3]
As tailwind becomes more flexible and classes are being constantly updated, it would be helpful to be able to use wildcards in the config classes_order section. For example mt-9 and mt-10 are part of tailwindcss, but are missing from the config file.

For example - instead of:
```
classes_order:
    - mt-0
    - mt-0-5
    - mt-0-75
    - mt-1
    - mt-1-5
    - mt-2
    - mt-2-5
    - mt-3
    - mt-4
    - mt-5
    - mt-6
    - mt-7
    - mt-8
```

write a regular expression or use a wildcard *
```
classes_order:
  - /mt-[0-9-]{1,}/
  - mt-*
```

**Comment by borama** [comment]
Hey Tim, thanks and sorry for the delay, I completely missed all notifications in this repo :sweat_smile: .

Anyway, I agree, I was pondering about a similar thing some time ago, too. I am now inclined to support regular expressions in the config and will implement it soon. Will let you know, thanks!

**Comment by borama** [comment]
OK, done in main, I'll soon release this in gem version 0.4, thanks!
